trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: techallylw/lacework-cli:ubuntu-1804

steps:
- script: lacework vul report sha256:fa31faba325ec777ad2a5d72689c4f9e1e31bc1e9bc3bd2fd98197e0d1125688 --details
  displayName: 'lacework-cli vulnerability report'
  env:
    LW_ACCOUNT: $(LW_ACCOUNT)
    LW_API_KEY: $(LW_API_KEY)
    LW_API_SECRET: $(LW_API_SECRET)
