trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: techallylw/lacework-cli:ubuntu-1804

steps:
- script: lacework vul report sha256:44ad1caa67566edf9f5ff5a4ffac5160ffe06db767fa284ebe816a04d601f494 --details
  displayName: 'lacework-cli vulnerability report'
  env:
    LW_ACCOUNT: $(LW_ACCOUNT)
    LW_API_KEY: $(LW_API_KEY)
    LW_API_SECRET: $(LW_API_SECRET)
